### ISSUE TITLE
如何添加生日

### ISSUE THREAD

**Issue by ghost** [xwl/cal-china-x#10]
你好。我想在agenda－list里面显示朋友的生日，要在哪里设置啊？还有那个学校里的周日历，能不能简单说一下要怎么设置啊？谢谢。

**Comment by xwl** [comment]
agenda-list 是 orgMode 的问题吧，我不太清楚。学校周日历设置这个就可以：cal-china-x-custom-week-start-date

**Comment by lxeg0429** [comment]
哦，好的，谢谢！
