### ISSUE TITLE
星期显示为英文缩写

### ISSUE THREAD

**Issue by infurth** [xwl/cal-china-x#11]
疑似372-376行对chinese-fonts-setup包的判断(我并不懂lisp),chinese-fonts-setup包因重名被作者更名为cnfonts(详见 https://github.com/tumashu/cnfonts#orgf6ad03e )。
本人将chinese-fonts-setup修改为cnfonts后重编译elc文件后,问题解决。

考虑到并非所有用户都会使用cnfonts进行对齐,最好加入一个选项让用户自己选择中/英文星期,或者干脆忽略对齐问题只显示中文星期,以免让用户疑惑。

另:编译时提示
‘calendar-font-lock-keywords’ is an obsolete
    variable (as of 24.4); set font-lock keywords in ‘calendar-mode-hook’,
    or customize calendar faces.
不知是否要将变量修改以更好兼容新版。

**Comment by xwl** [comment]
Fixed in https://github.com/xwl/cal-china-x/commit/3cd8288562eaebf47163431c3d908fc4ed469644 

1. 加了对 'cnfonts 的检测。
2. 新的变量 cal-china-x-force-chinese-week-day
3. Warning 亦已修复

谢谢反馈。
