### ISSUE TITLE
void-variable calendar-font-lock-keywords

### ISSUE THREAD

**Issue by damon-kwok** [xwl/cal-china-x#12]
OS: ubuntu 16.04.3
emacs: 27.0.50

Error:
Debugger entered--Lisp error: (void-variable calendar-font-lock-keywords)
  (append calendar-font-lock-keywords '(("[0-9]+年\\ *[0-9]+月" . font-lock-function-name-face)))
  (setq calendar-font-lock-keywords (append calendar-font-lock-keywords '(("[0-9]+年\\ *[0-9]+月" . font-lock-function-name-face))))
  eval((setq calendar-font-lock-keywords (append calendar-font-lock-keywords '(("[0-9]+年\\ *[0-9]+月" . font-lock-function-name-face)))) nil)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)

**Comment by c0001** [comment]
The same in archlinux !
emacs version :
     GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.26) of 2018-01-31

And fine in 25.3 version, with I checkout the variable 'calendar-font-lock-keywords' is not found in emacs 27.

So, Could you update it to be compitable for higher emacs version?

**Comment by xwl** [comment]
Thanks for reporting. Fixed by https://github.com/xwl/cal-china-x/commit/2a8d6de93ccb892660fdb5e397196fd8f42df152

Please check.

**Comment by c0001** [comment]
All be fine , thank you for fixing:)
