### ISSUE TITLE
cal-china-x-birthday-from-chinese

### ISSUE THREAD

**Issue by xarthurx** [xwl/cal-china-x#13]
這個我理解是算陰曆生日的當年陽曆生日。

然而現在是公元2018年2月8日，陰曆還沒過年。如果輸入陰曆生日，算的下一個是2017年的陽曆生日。
這個算法是不是出了bug？

**Comment by xwl** [comment]
Fixed in https://github.com/xwl/cal-china-x/commit/e9b309065829af3a9a0c526509bd64d9228fdced

谢谢反馈。
