### ISSUE TITLE
void-variable calendar-font-lock-keywords

### ISSUE THREAD

**Issue by soulspirits** [xwl/cal-china-x#16]
Hi,
After I upgrade my emacs version on Ubuntu18.04 from 26.3 to 27,there is an error pop-up at startup.The following message is the content of traceback buffer. Would you think about this is an bug for cal-china-x? Thanks for the effort.

Stephen.
-----message from traceback buffer---
Debugger entered--Lisp error: (void-variable calendar-font-lock-keywords)
  (append calendar-font-lock-keywords '(("[0-9]+年\\ *[0-9]+月" . font-lock-function-name-face)))
  (setq calendar-font-lock-keywords (append calendar-font-lock-keywords '(("[0-9]+年\\ *[0-9]+月" . font-lock-function-name-face))))
  cal-china-x-setup()
  eval-buffer(#<buffer  *load*-928930> nil "/home/stephen/.emacs.d/lisp/cal-china-x/cal-china-..." nil t)  ; Reading at buffer position 22134
  load-with-code-conversion("/home/stephen/.emacs.d/lisp/cal-china-x/cal-china-..." "/home/stephen/.emacs.d/lisp/cal-china-x/cal-china-..." nil t)
  require(cal-china-x)
  eval-buffer(#<buffer  *load*-411382> nil "/home/stephen/.emacs.d/lisp/init-better-defaults.e..." nil t)  ; Reading at buffer position 983
  load-with-code-conversion("/home/stephen/.emacs.d/lisp/init-better-defaults.e..." "/home/stephen/.emacs.d/lisp/init-better-defaults.e..." nil t)
  require(init-better-defaults)
  eval-buffer(#<buffer  *load*> nil "/home/stephen/.emacs" nil t)  ; Reading at buffer position 292
  load-with-code-conversion("/home/stephen/.emacs" "/home/stephen/.emacs" t t)
  load("~/.emacs" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0x158cf799d1c5>) #f(compiled-function () #<bytecode 0x158cf799d1d9>) t)
  command-line()
  normal-top-level()

**Comment by xwl** [comment]
Probably it gets renamed in 27. I will have a look.

**Comment by xwl** [comment]
actually it was already fixed in 2a8d6de93ccb892660fdb5e397196fd8f42df152 last year. You need to upgrade your cal-china-x to the latest version.
