### ISSUE TITLE
Feature Request: 增加关闭星座的选项

### ISSUE THREAD

**Issue by pmeiyu** [xwl/cal-china-x#17]
希望增加关闭星座的选项，最好换成节气。十二星座是西方的占星文化，和天干地支纪年放在一起显得不伦不类。

**Comment by xwl** [comment]
节气已经支持了，会出现在星座后面。

**Comment by pmeiyu** [comment]
> 节气已经支持了，会出现在星座后面。

现在只会在节气开始的那天显示节气，查某天的节气很麻烦，需要一直向前翻。节气并不只是一天，而是一段时间，和十二星座类似。

**Comment by xwl** [comment]
Add option for always showing JieQi: https://github.com/xwl/cal-china-x/commit/b0661e1655ea254c4afeff029916fe08928063e9

**Comment by xwl** [comment]
no more comment, closing this.
