### ISSUE TITLE
loop or cl-loop?

### ISSUE THREAD

**Issue by tumashu** [xwl/cal-china-x#18]
https://github.com/xwl/cal-china-x/blob/b0661e1655ea254c4afeff029916fe08928063e9/cal-china-x.el#L489

**Comment by xwl** [comment]
From the doc: "loop is an alias for ‘cl-loop’ in ‘cl.el’."

**Comment by tumashu** [comment]
the problem is that cal-china-x require cl-lib instead of cl :-)

在 2020-09-17 01:56:00，"William Xu" <notifications@github.com> 写道：


From the doc: "loop is an alias for ‘cl-loop’ in ‘cl.el’."

**Comment by xwl** [comment]
I looked into cl.el, it will "(require 'cl-lib)"... I guess "cl.el" is loaded automatically? or by some other packages. I think the fix would be replace 'loop' with 'cl-loop' here. 

Thanks for pointing it out.

**Comment by xwl** [comment]
fixed with 98d965efe8fcbec4fe0092d9ef3a0d7bfeef8ffc
