### ISSUE TITLE
节气不显示了

### ISSUE THREAD

**Issue by noirchen** [xwl/cal-china-x#2]
以前1.1版的时候节气能在状态栏上显示，但是现在不再显示了，怎么调出来呢？

**Comment by xwl** [comment]
我对比了一年的节气，确实有些会存在一两天的误差。要控制所有误差貌似并不是很容易.. 我看看能不能改进改进.

**Comment by xwl** [comment]
Fixed in 5292a988494df85f014e0e1c303fb36b90fb3a62

对于 1901-2100 这两百年，我直接使用别人算好的值，这样可以保证这两百年的时间是准确的。至于别的年份，计算仍然会有一两天的误差。

**Comment by xwl** [comment]
另外，这个算好的值是以东八区即北京时区为准。
