### ISSUE TITLE
modeline显示不全

### ISSUE THREAD

**Issue by vinurs** [xwl/cal-china-x#20]
好像跟英文节日一起显示的时候状态栏有时候不能显示完全
![image](https://user-images.githubusercontent.com/37489300/110896250-2c525d00-8336-11eb-8f25-85e1f25d54d6.png)

**Comment by xwl** [comment]
你可以调整 mode line 长度，比如 (setq calendar-right-margin 120)

**Comment by vinurs** [comment]
好了，谢谢
