### ISSUE TITLE
与 calendar-day-abbrev-array 设置有冲突

### ISSUE THREAD

**Issue by lixuzhang** [xwl/cal-china-x#3]
加载了cal-china-x后，我设置的calendar-day-abbrev-array变得无效，日历月份标题变成calendar-day-name-array的第一个汉字。

是否在函数 calendar-day-abbrev-array 中以下代码导致？

;; Use the first two characters of each day to head the columns.
    (dotimes (i 7)
      (insert
       (progn
         (setq string
               (calendar-day-name (mod (+ calendar-week-start-day i) 7) nil t))
         ;; (cal-china-x-day-short-name (mod (+ calendar-week-start-day i) 7)))
         (if enable-multibyte-characters
             (truncate-string-to-width string calendar-day-header-width)
           (substring string 0 calendar-day-header-width)))
       (make-string (- calendar-column-width calendar-day-header-width) ?\s)))

**Comment by xwl** [comment]
你的设置，以及 emacs version 是什么？

**Comment by lixuzhang** [comment]
;; calendar.el --- calendar functions
(req-package calendar
  :init (progn
          (setq diary-file "~/life/diary")
          ;; Week days
          (setq calendar-week-start-day 0) ; 0:星期天, 1:星期一
          (setq calendar-date-style 'iso)
          (setq calendar-day-name-array
                ["星期日" "星期一" "星期二" "星期三" "星期四" "星期五" "星期六"])
          (setq calendar-day-abbrev-array
                ["日" "一" "二" "三" "四" "五" "六"])
          (setq calendar-day-header-array
                ["日" "一" "二" "三" "四" "五" "六"])
          ;; Month
          (setq calendar-month-name-array
                ["一月" "二月" "三月" "四月" "五月" "六月"
                 "七月" "八月" "九月" "十月" "十一月" "十二月"])
          (setq calendar-month-abbrev-array
                ["一月" "二月" "三月" "四月" "五月" "六月"
                 "七月" "八月" "九月" "十月" "十一" "十二"])
          (setq calendar-chinese-all-holidays-flag t)
          (setq calendar-mark-diary-entries-flag t)
          (setq calendar-mark-holidays-flag t)
          ;; lunar.el --- calendar functions for phases of the moon
          (setq lunar-phase-names '("新月" "上弦月" "满月" "下弦月"))
          ;; holidays.el --- holiday functions for the calendar package
          (setq calendar-chinese-celestial-stem   ; 天干
                ["甲" "乙" "丙" "丁" "戊" "已" "庚" "辛" "壬" "癸"])
          (setq calendar-chinese-terrestrial-branch ; 地支
                ["子" "丑" "寅" "卯" "辰" "巳" "午" "未" "申" "酉" "戌" "亥"])
          (setq calendar-chinese-month-name-array
                ["正月" "二月" "三月" "四月" "五月" "六月" "七月" "八月" "九月" "十月" "冬月" "腊月"])
          (setq holiday-general-holidays
                '((holiday-fixed 1 1 "新年")
                  (holiday-fixed 3 8 "妇女节")
                  (holiday-fixed 5 1 "劳动节")
                  (holiday-fixed 5 4 "青年节")
                  (holiday-fixed 6 1 "儿童节")
                  (holiday-fixed 9 10 "教师节")
                  (holiday-fixed 10 1 "国庆节")))
          (setq holiday-other-holidays
                '((holiday-fixed 2 14 "情人节")
                  (holiday-fixed 3 12 "植树节")
                  (holiday-fixed 4 1 "愚人节")
                  (holiday-float 5 0 2 "母亲节")
                  (holiday-float 6 0 3 "父亲节")
                  (holiday-fixed 10 31 "万圣节")
                  (holiday-fixed 11 11 "光棍节")
                  (holiday-float 11 4 4 "感恩节")
                  (holiday-fixed 12 25 "圣延节")))
          ;; cal-china.el --- calendar functions for the Chinese calendar
          (setq holiday-oriental-holidays    ; 传统节日
                '((holiday-chinese-new-year) ; "春节"
                  (holiday-chinese-qingming) ; "清明"
                  (holiday-chinese 5 5 "端午")
                  (holiday-chinese 7 7 "七夕")
                  (holiday-chinese 8 15 "中秋")
                  (holiday-chinese 9 9 "重阳")
                  (holiday-chinese-winter-solstice) ; "冬至"
                  (holiday-chinese 12 30 "除夕"))))
  :config (progn
            (require 'holidays)
            (require 'cal-china)
            (setq calendar-holidays
                  (append holiday-general-holidays
                          holiday-other-holidays
                          holiday-oriental-holidays
                          holiday-local-holidays))
            (require 'appt) ;; appt.el --- appointment notification functions
            (appt-activate t)))

==========
后面只要加载 cal-china-x 就会导致calendar-day-abbrev-array无效，日历的标题变成
“星 星 星 星 星 星 星”这样，是直接从calendar-day-name-array截取而不是用calendar-day-abbrev-array；如果calendar-day-name-array设成“周日、周一……”，加载了cal-china-x后日历标题就变成“周 周 周 周 周 周 周”这样。

  (req-package cal-china-x
    :config
    (setq calendar-day-name-array
          ["日" "一" "二" "三" "四" "五" "六"]) ; 加载cal-china-x后calendar-day-abbrev-array不起作用
    (setq cal-china-x-important-holidays
          cal-china-x-chinese-holidays)   ; 法定假日
    (setq holiday-oriental-holidays
          '((holiday-lunar 1 1 "春节" 0)
            (holiday-solar-term "清明" "清明")
            (holiday-lunar 5 5 "端午" 0)
            (holiday-lunar 7 7 "七夕")
            (holiday-lunar 8 15 "中秋" 0)
            (holiday-lunar 9 9 "重阳")
            (holiday-solar-term  "冬至"  "冬至")
            (holiday-lunar 12 30 "除夕")))
    (setq calendar-holidays
          (append holiday-general-holidays
                  holiday-local-holidays
                  holiday-other-holidays
                  holiday-oriental-holidays)))

==========
GNU Emacs 25.0.50.1 (x86_64-w64-mingw32) of 2015-05-13 on CAB8
用msys2自带的64位git版（现在的官方库好像已经取消）

==========
我不加载cal-china-x时，日历标题是正常显示出“日 一 二 三 四 五 六”的；然后一旦加载cal-china-x后就会变成“星 星 星 星 星 星 星”这样。

**Comment by xwl** [comment]
Fixed in fdf965c55c182e349e3a2748722e995d03913057

不过因为中文字体和英文字体大小的差异，估计比较难做到对齐。

**Comment by lixuzhang** [comment]
用 chinese-fonts-setup 可以解决字体对齐问题，melpa有包可自动安装。
源代码地址 https://github.com/tumashu/chinese-fonts-setup

**Comment by xwl** [comment]
那你用最新的cal-china-x解决你的问题了吗

LI Xuzhang <notifications@github.com> schrieb am Do., 5. Nov. 2015 um 15:42:

**Comment by lixuzhang** [comment]
已经解决星期日到六标题行的显示问题，现在正常显示为“日 一 二 三 ……”了。

不过，由于我开启了中英文间加空格模式（https://github.com/coldnew/pangu-spacing），年月标题被自动加空格后发生了位置偏移。我重新设置成下面这样（中英文间加空格）就没事了：
(setq calendar-month-header '(propertize (format "%d 年 %d 月" year month)
                                             'font-lock-face
                                             'calendar-month-header))
