### ISSUE TITLE
能提交到 MELPA 吗？

### ISSUE THREAD

**Issue by pixode** [xwl/cal-china-x#4]
https://github.com/milkypostman/melpa
谢谢啦

**Comment by xwl** [comment]
我看看怎么申请。。
pixode <notifications@github.com> schrieb am Mi., 28. Okt. 2015 um 15:59:

**Comment by lixuzhang** [comment]
我在emacs中看到有这包有一段时间了，只是旧版的没更新，不是你做的？

cal-china-x is an installed package.

     Status: Installed in `~/.emacs.d/elpa/cal-china-x-20140907.855/' (unsigned).
    Archive: n/a
    Version: 20140907.855
    Summary: Chinese calendar extras
   Homepage: http://xwl.appspot.com/ref/cal-china-x.el
    Other versions: 20140907.155 (melpa).

**Comment by xwl** [comment]
不是我做的。谁有经验，欢迎提 patch...  我已经 clone 了 https://github.com/xwl/melpa

**Comment by pixode** [comment]
如果没弄错的话，应该是你发布的第一个 emacswiki 版本吧？而且也在一直维护。
>2006-05-20
12:01 UTC (new) cal-china-x.el . . . . WilliamXWL – new file. [en]

[点击这个链接](https://github.com/milkypostman/melpa/edit/master/recipes/cal-china-x)，把原内容改为：
```emacs-lisp
(cal-china-x :repo "xwl/cal-china-x" :fetcher github)
```
标题和内容的话这样写不知行不行：
>Fetching cal-china-x from GitHub

>The official location for cal-china-x has been moved from [Emacswiki](http://www.emacswiki.org/emacs/cal-china-x.el) to [xwl/cal-china-x](https://github.com/xwl/cal-china-x), in order to get proper version control.

**Comment by xwl** [comment]
已提交 merge request, 等待更新中。。

**Comment by pixode** [comment]
MELPA 已经更新了，3Q
