### ISSUE TITLE
农历节日未在日历上高亮显示，calendar-list-holidays变量报错

### ISSUE THREAD

**Issue by ziyuanjun** [xwl/cal-china-x#8]
图片可以在[这里](https://emacs-china.org/t/gtd/1365/5)看到（我不知道github怎么上图）。
查看calendar-list-holidays变量看到了许多错误：

> Error (holidays): Bad holiday list item: (holiday-fixed 1 1 元旦)
> Error: (void-variable displayed-month)
> 
> Error (holidays): Bad holiday list item: (holiday-lunar 12 30 春节 0)
> Error: (void-variable displayed-month)
> ....

每个农历节日都有Error。

emacs-version is:  GNU Emacs 25.1.50.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.10.8)
cal-china-x是刚刚装的。

**Comment by ziyuanjun** [comment]
我知道了，用x打开高亮显示，可那个error是怎么回事？

**Comment by xwl** [comment]
设置了 (setq calendar-mark-holidays-flag t) 就不用输入 x, 而是自动高亮了。

你试试下面的步骤会不会重现：
1. emacs -Q
2. 打开 cal-china-x.el, M-x eval-buffer
3. M-: (setq calendar-mark-holidays-flag t)
4. M-x calendar
