### ISSUE TITLE
同一天不能定义多个节日吗？

### ISSUE THREAD

**Issue by vinurs** [xwl/cal-china-x#9]
可能同一天会有好几个要关注的节日，貌似现在后一个会覆盖前面的一个定义，有办法支持同一天定义多个节日吗？

**Comment by xwl** [comment]
目前没有这个支持。不过可以只定义一次，列出所有当天的节日？比如：

     (holiday-fixed 10 1 "国庆节 || 生日")

**Comment by vinurs** [comment]
这样定义太丑了，显示起来也不好看。

**Comment by xwl** [comment]
我之前说错了。我试了一下，在同一天定义多次是没有问题的。比如：

        (holiday-lunar 7 7  "七夕节")
        (holiday-lunar 7 7  "QiXi")

在 mode line 可以同时看到两者: "QiXi 七夕节".  如果 M-x calendar-list-holidays, 则能看到：

2016年08月09日 星期二: QiXi
2016年08月09日 星期二: 七夕节
